//cspell:disable

const ROOT_URL =
	'https://res.cloudinary.com/taylor1119/image/upload/v1736698859'

const imageSources = {
	logo: `${ROOT_URL}/fl0huqn0uiw7tua3tkk8.jpg`,
	projects: {
		'social-media-app': [
			`${ROOT_URL}/social-media-app/ge94ejbf9zke4xw2xo9w.webp`,
			`${ROOT_URL}/social-media-app/jqgu6nu1iuq8mp45bm5d.webp`,
			`${ROOT_URL}/social-media-app/yfraxhtu1ib5zcz9novc.webp`,
			`${ROOT_URL}/social-media-app/mrjgnximt6poh9jkaxul.webp`,
			`${ROOT_URL}/social-media-app/iqgcbbeb8xg9996fsj82.webp`,
			`${ROOT_URL}/social-media-app/cqtiinodmk312cxq5pej.webp`,
			`${ROOT_URL}/social-media-app/jmyq8so6rfeqge8tpxrr.webp`,
			`${ROOT_URL}/social-media-app/goqdsf9favtjy1coabkl.webp`,
			`${ROOT_URL}/social-media-app/tcasytdvc0mleyvckhmz.webp`,
			`${ROOT_URL}/social-media-app/tx0ngyh1qdysn7qfz750.webp`,
		],
		'e-commerce-app': [
			`${ROOT_URL}/e-commerce-app/g0cks92xdobjpnm2uros.webp`,
			`${ROOT_URL}/e-commerce-app/qcaxub9pfd5bqsk6kkmu.webp`,
			`${ROOT_URL}/e-commerce-app/ekcx8bwlmm5jdx0xdoab.webp`,
			`${ROOT_URL}/e-commerce-app/j9d8ocabgc7ijypshsgj.webp`,
			`${ROOT_URL}/e-commerce-app/teyc6nwai3mqvjw21vby.webp`,
			`${ROOT_URL}/e-commerce-app/qw8lof8vwzlq29bggsbr.webp`,
			`${ROOT_URL}/e-commerce-app/lwkroe1n8ly6lvou3db2.webp`,
			`${ROOT_URL}/e-commerce-app/ma8sjoplgklmdklbhzgi.webp`,
			`${ROOT_URL}/e-commerce-app/kqefdmecaf6ibhoh4jo9.webp`,
		],
		'messaging-app': [
			`${ROOT_URL}/messaging-app/tjtw1szksimfm8fhy7pj.webp`,
			`${ROOT_URL}/messaging-app/gfqdpqxy2hh6hip1fjaf.webp`,
			`${ROOT_URL}/messaging-app/su65xguv2b2i4ie3u8pw.webp`,
			`${ROOT_URL}/messaging-app/q6jybuyvch5uvnvj9l8m.webp`,
			`${ROOT_URL}/messaging-app/eqnpfibb3wiuyguplgst.webp`,
			`${ROOT_URL}/messaging-app/eaiugueq53rl2kol2u0n.webp`,
		],
		'dashboard-nextjs': [
			`${ROOT_URL}/dashboard-nextjs/xew8lgarqesjsad0mirg.webp`,
			`${ROOT_URL}/dashboard-nextjs/xgcyub0ky7v39wvnhepm.webp`,
			`${ROOT_URL}/dashboard-nextjs/tppbgheoru6yrjwid3gd.webp`,
			`${ROOT_URL}/dashboard-nextjs/cyaukawk0fmknzvqylvx.webp`,
			`${ROOT_URL}/dashboard-nextjs/r7z1dvhiqhqxoydd9nqc.webp`,
			`${ROOT_URL}/dashboard-nextjs/kpdvrnwoytsvyoyg9w3r.webp`,
		],
		'airbnb-clone': [
			`${ROOT_URL}/airbnb-clone/xb1ahndtkjcl4hi1scih.webp`,
			`${ROOT_URL}/airbnb-clone/ssohmqf4dldz9y3mr5za.webp`,
			`${ROOT_URL}/airbnb-clone/hkakyd79si6r3ix7otwf.webp`,
			`${ROOT_URL}/airbnb-clone/rg2zjkoh1eiu44cw8rae.webp`,
			`${ROOT_URL}/airbnb-clone/lpxgoplaqzrmuzxyyvyd.webp`,
			`${ROOT_URL}/airbnb-clone/fnnmcffrdlwngek44fqw.webp`,
			`${ROOT_URL}/airbnb-clone/jmvmgu75tpz0sxeq2wjy.webp`,
		],
		'memory-matching-game': [
			`${ROOT_URL}/memory-matching-game/f23oxosv87dcmvxu4oyl.webp`,
		],
		'cash-flow': [
			`${ROOT_URL}/cash-flow/yetrqatbbbsrwnyeiz3g.webp`,
			`${ROOT_URL}/cash-flow/g054cdf7wjrc06bobhau.webp`,
			`${ROOT_URL}/cash-flow/uxvszzv1wrnhrxsrxgfw.webp`,
			`${ROOT_URL}/cash-flow/xdpzsbebouvl8tsq4h9l.webp`,
			`${ROOT_URL}/cash-flow/r2xgnijdyura0gqufdym.webp`,
			`${ROOT_URL}/cash-flow/fvf7pfidsozwbj9av4a4.webp`,
			`${ROOT_URL}/cash-flow/oetjaw8p5ldexc1ltzoh.webp`,
			`${ROOT_URL}/cash-flow/nryljkbflf7rg7amp3jt.webp`,
		],
		'events-admin': [
			`${ROOT_URL}/events-admin/nuthktwyerifbbik5jaf.webp`,
			`${ROOT_URL}/events-admin/vuaa373sitqdk6egogsd.webp`,
			`${ROOT_URL}/events-admin/vq5nut4zfbjyfdkfk9pv.webp`,
			`${ROOT_URL}/events-admin/chxoqpt9cjeexieptmqv.webp`,
			`${ROOT_URL}/events-admin/jlue93s7fjqz3efnmakv.webp`,
			`${ROOT_URL}/events-admin/dghrqtsldvc7haqafesm.webp`,
		],
		'events-exhibit': [
			`${ROOT_URL}/events-exhibit/pdsg6rgmjwfpgbxu4hvu.webp`,
			`${ROOT_URL}/events-exhibit/ftpkmpn3yfghi7dfgx75.webp`,
			`${ROOT_URL}/events-exhibit/rfnuu4xbi6cbisixxunm.webp`,
			`${ROOT_URL}/events-exhibit/gvdvkdpgoison2rajfa6.webp`,
			`${ROOT_URL}/events-exhibit/vkj3rkuz4izaawfkoqgu.webp`,
			`${ROOT_URL}/events-exhibit/qzqzh80zut4qqrwfv2r4.webp`,
			`${ROOT_URL}/events-exhibit/zp57trrvd88iojekqqod.webp`,
		],
		'bookdex': [
			`${ROOT_URL}/bookdex/xnsio6h8rikd15n2g9si.webp`,
			`${ROOT_URL}/bookdex/g8flaozuhh27pc75ylcx.webp`,
			`${ROOT_URL}/bookdex/jse0fssfpk8vzvvuljun.webp`,
			`${ROOT_URL}/bookdex/uzjuuarlgogw4tonag5a.webp`,
			`${ROOT_URL}/bookdex/liac8ya78mnoevoopfxn.webp`,
			`${ROOT_URL}/bookdex/lrs4ltrqp45ndd3lyald.webp`,
			`${ROOT_URL}/bookdex/odhowczqccatgdoi1zvc.webp`,
			`${ROOT_URL}/bookdex/khymflbtchgidcmq0a28.webp`,
		],
		'brainwave': [
			`${ROOT_URL}/brainwave/udreaznv8gcyaj3cuswo.webp`,
			`${ROOT_URL}/brainwave/b5habflah7wlobzczyym.webp`,
			`${ROOT_URL}/brainwave/j5nfyekq1vjtly46khnh.webp`,
			`${ROOT_URL}/brainwave/gxhhvsglhdubwphq718p.webp`,
			`${ROOT_URL}/brainwave/xhe6fh15xya4kglulcds.webp`,
			`${ROOT_URL}/brainwave/hgaelszazphsl2ewwz5z.webp`,
		],
		'landing-page': [
			`${ROOT_URL}/landing-page/xgnhvs8owykqnsj5uqts.webp`,
			`${ROOT_URL}/landing-page/gokbuhn57bytgccgo4q8.webp`,
			`${ROOT_URL}/landing-page/upvwwbqiualmxqdfai9r.webp`,
			`${ROOT_URL}/landing-page/wdbw3nzmldmz6w0abkbc.webp`,
			`${ROOT_URL}/landing-page/xykdnb3tnhbcjnkpjpr2.webp`,
		],
	},
}

export default imageSources
